#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("YandexMapTest.Resource", IsApplication=true)]

namespace YandexMapTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drag1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drag2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int kreml = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int shop = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int yandex = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int yandex2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ymk_balloon_black = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ymk_balloon_tail_black = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ymk_balloon_text_color = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ymk_empty_image = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ymk_find_me_drawable = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ymk_no_map_image = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ymk_scale = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ymk_sgrayvga = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ymk_sgreenvga = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ymk_sredvga = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ymk_stricolorvga = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ymk_syellowvga = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ymk_tlight_loading = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ymk_tlight_no_level_active = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ymk_tlight_no_level_active_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ymk_tlight_no_level_inactive = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ymk_tlight_no_level_inactive_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ymk_tlight_no_level_loading_1 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ymk_tlight_no_level_loading_2 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ymk_tlight_no_level_loading_3 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ymk_user_location_gps = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ymk_user_location_lbs = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ymk_where_am_i = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ymk_where_am_i_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ymk_ya_logo = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ymk_zoom_minus = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ymk_zoom_minus_drawable = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ymk_zoom_minus_pressed = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ymk_zoom_plus = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ymk_zoom_plus_drawable = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ymk_zoom_plus_pressed = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int map = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int myButton = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int ymk_balloon_text_view = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int ymk_find_me = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int ymk_scale = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int ymk_screen_buttons_bottom = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int ymk_screen_buttons_top = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int ymk_semaphore = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int ymk_zoom_in = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int ymk_zoom_out = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ymk_balloon_default_layout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ymk_screen_buttons_layout = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060006
			public const int app_name = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int hello = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int ymk_findme_not_found = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int ymk_kilometers_short = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int ymk_lang = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int ymk_meters_short = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ymk_my_place = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int ymk_map_layers = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
